# name: Docker Image CI (Alpha)

# on:
#   push:
#     branches-ignore:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag draft-my-cv:$(date +%s)