services:
  draft-my-cv:
    build:
      context: .
      target: development
    image: draft-my-cv-development
    container_name: draft-my-cv-development
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json